pages:
  stage: deploy
  tags:
    - docker
    - amd64
  image: python:3.10-alpine
  script:
    - cd doc
    - pip install -r requirements.txt
    - sphinx-build -b html . ../pages
    - cd ./..
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

