pages:
  stage: deploy
  tags:
    - docker
    - amd64
  image: python:3.10-alpine
  script:
    - pip install -r doc/requirements.txt
    - sphinx-build -b html doc public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

